baseURL = 'http://example.com/'
languageCode = 'en-US'
title = 'Nyong Hugo Theme'
theme = 'nyong'

# Show how many post of page
paginate = 5

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  subtitle = 'Simple Fast and SEO Friendly Hugo Theme'
  description = 'Simple Fast, SEO Friendly Hugo Theme'
  keywords = [
    'Fast and Clean Hugo Theme SEO Friendly',
    'Simple and Fast Hugo Theme Free'
  ]
  dateFormat = 'January 2, 2006'

[social]
  twitter = 'sunuazizrahayu'