# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "nyong"
          replace: "nyong-hugo-theme"
          include: "exampleSite/config.toml"
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "http://example.com"
          replace: "https://sunuazizrahayu.github.io/nyong-hugo-theme"
          include: "exampleSite/config.toml"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build
        run: cd exampleSite && hugo --themesDir=../.. --minify --environment=production
      - run: ls -la
      - run: ls -la exampleSite || true

      - uses: actions/upload-artifact@master
        with:
          name: build-result
          path: exampleSite/public


  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build-result
          path: exampleSite/public

      - run: ls -la
      - run: ls -la exampleSite || true
      - run: ls -la exampleSite/public || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'exampleSite/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
